import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Every artifact the emitter writes carries this line, and `gen.mjs --check`
 * compares bytes. If a human edits a generated file, the gate fails instead of
 * the next run silently reverting the edit.
 */
export const header = (source) => `@generated by uiautomation/pipeline from ${source}. Do not edit by hand.`;

export const readJson = (relPath) => JSON.parse(readFileSync(resolve(ROOT, relPath), 'utf8'));
export const readText = (relPath) => readFileSync(resolve(ROOT, relPath), 'utf8');

/** Sorted keys everywhere: byte-identical output no matter how JSON was authored. */
export function stableStringify(value) {
	return `${JSON.stringify(sortKeys(value), null, '\t')}\n`;
}

function sortKeys(value) {
	if (Array.isArray(value)) return value.map(sortKeys);
	if (value && typeof value === 'object') {
		return Object.fromEntries(Object.keys(value).sort().map((key) => [key, sortKeys(value[key])]));
	}
	return value;
}

export function writeOut(relPath, contents) {
	const abs = resolve(ROOT, relPath);
	mkdirSync(dirname(abs), { recursive: true });
	writeFileSync(abs, contents.endsWith('\n') ? contents : `${contents}\n`);
}

/** Compare rendered bytes against what is on disk; returns human-readable problems. */
export function compareOutputs(outputs) {
	const problems = [];
	for (const [path, contents] of outputs) {
		let current;
		try {
			current = readFileSync(resolve(ROOT, path), 'utf8');
		} catch {
			problems.push(`${path}: missing`);
			continue;
		}
		if (current !== contents) problems.push(`${path}: ${firstDifference(current, contents)}`);
	}
	return problems;
}

/** Generated files that nothing generates any more. */
export function staleOutputs(outputs) {
	const problems = [];
	const walk = (dir) => {
		for (const entry of readdirSync(dir)) {
			const abs = resolve(dir, entry);
			if (statSync(abs).isDirectory()) {
				walk(abs);
				continue;
			}
			const rel = abs.slice(resolve(ROOT).length + 1);
			if (!outputs.has(rel)) problems.push(`${rel}: stale (nothing generates this file)`);
		}
	};
	try {
		walk(resolve(ROOT, 'generated'));
	} catch {
		// generated/ does not exist yet
	}
	return problems;
}

function firstDifference(current, expected) {
	const a = current.split('\n');
	const b = expected.split('\n');
	for (let i = 0; i < Math.max(a.length, b.length); i++) {
		if (a[i] !== b[i]) {
			return `line ${i + 1} differs\n      on disk: ${JSON.stringify(a[i] ?? '<eof>')}\n      emitted: ${JSON.stringify(b[i] ?? '<eof>')}`;
		}
	}
	return 'differs';
}

export function parseArgv(argv) {
	const flags = {};
	const positional = [];
	for (let i = 0; i < argv.length; i++) {
		if (argv[i].startsWith('--')) {
			const key = argv[i].slice(2);
			const next = argv[i + 1];
			if (next && !next.startsWith('--')) {
				flags[key] = next;
				i++;
			} else {
				flags[key] = true;
			}
		} else {
			positional.push(argv[i]);
		}
	}
	return { flags, positional };
}

/**
 * Findings carry the gate that produced them, so `report.json` can tell the
 * playground (and CI) which gate a warning came from instead of dumping a list.
 */
export class Diagnostics {
	errors = [];
	warnings = [];

	error(message, gate = this.defaultGate) {
		this.errors.push({ gate, message });
	}

	warn(message, gate = this.defaultGate) {
		this.warnings.push({ gate, message });
	}

	get ok() {
		return this.errors.length === 0;
	}

	report(label) {
		for (const { gate, message } of this.warnings) console.warn(`  warn  [${gate}] ${message}`);
		for (const { gate, message } of this.errors) console.error(`  ERROR [${gate}] ${message}`);
		if (this.ok) {
			const gates = [...new Set(this.warnings.map((warning) => warning.gate))];
			console.log(`${label}: ${this.warnings.length} warning(s) across ${gates.length} gate(s), 0 errors`);
		}
		return this.ok;
	}
}

export function countByGate(entries) {
	const counts = {};
	for (const { gate } of entries) counts[gate] = (counts[gate] ?? 0) + 1;
	return counts;
}
